# Generated by Django 2.2.4 on 2021-03-19 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ncwellwise_subset_20102019_geom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid10', models.TextField(verbose_name=2)),
                ('arsenic_mean', models.FloatField(null=True)),
                ('arsenic_minimum', models.FloatField(null=True)),
                ('arsenic_maximum', models.FloatField(null=True)),
                ('arsenic_std', models.FloatField(null=True)),
                ('cadmium_mean', models.FloatField(null=True)),
                ('cadmium_minimum', models.FloatField(null=True)),
                ('cadmium_maximum', models.FloatField(null=True)),
                ('cadmium_std', models.FloatField(null=True)),
                ('lead_mean', models.FloatField(null=True)),
                ('lead_minimum', models.FloatField(null=True)),
                ('lead_maximum', models.FloatField(null=True)),
                ('lead_std', models.FloatField(null=True)),
                ('manganese_mean', models.FloatField(null=True)),
                ('manganese_minimum', models.FloatField(null=True)),
                ('manganese_maximum', models.FloatField(null=True)),
                ('manganese_std', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'drf_ncwellwise_subset_20102019_geom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ncwellwise_subset_20102019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid10', models.TextField(verbose_name=2)),
                ('arsenic_mean', models.FloatField(null=True)),
                ('arsenic_minimum', models.FloatField(null=True)),
                ('arsenic_maximum', models.FloatField(null=True)),
                ('arsenic_std', models.FloatField(null=True)),
                ('cadmium_mean', models.FloatField(null=True)),
                ('cadmium_minimum', models.FloatField(null=True)),
                ('cadmium_maximum', models.FloatField(null=True)),
                ('cadmium_std', models.FloatField(null=True)),
                ('lead_mean', models.FloatField(null=True)),
                ('lead_minimum', models.FloatField(null=True)),
                ('lead_maximum', models.FloatField(null=True)),
                ('lead_std', models.FloatField(null=True)),
                ('manganese_mean', models.FloatField(null=True)),
                ('manganese_minimum', models.FloatField(null=True)),
                ('manganese_maximum', models.FloatField(null=True)),
                ('manganese_std', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='triangle_tracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('statefp10', models.TextField(null=True, verbose_name=2)),
                ('countyfp10', models.TextField(null=True, verbose_name=3)),
                ('tractce10', models.TextField(null=True, verbose_name=6)),
                ('geoid10', models.TextField(null=True, verbose_name=11)),
                ('name10', models.TextField(null=True, verbose_name=7)),
                ('namelsad10', models.TextField(null=True, verbose_name=20)),
                ('mtfcc10', models.TextField(null=True, verbose_name=5)),
                ('funcstat10', models.TextField(null=True, verbose_name=1)),
                ('aland10', models.FloatField(null=True)),
                ('awater10', models.FloatField(null=True)),
                ('intptlat10', models.TextField(null=True, verbose_name=11)),
                ('intptlon10', models.TextField(null=True, verbose_name=12)),
                ('layer', models.TextField(null=True, verbose_name=254)),
                ('path', models.TextField(null=True, verbose_name=254)),
            ],
        ),
    ]
