# Generated by Django 3.1.7 on 2021-04-06 20:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nc_covid_zipcode_geom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.TextField(verbose_name=5)),
                ('cases', models.IntegerField()),
                ('cases_per_10000_res', models.FloatField(null=True)),
                ('cases_per_100000_res', models.FloatField(null=True)),
                ('deaths', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'drf_nc_covid_zipcode_geom',
                'managed': False,
            },
        ),
    ]
