# Generated by Django 3.1.7 on 2021-04-08 00:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_nc_covid_zipcode_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ncwellwise_triangle_20102019_geom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoid10', models.TextField(verbose_name=2)),
                ('arsenic_mean', models.FloatField(null=True)),
                ('arsenic_minimum', models.FloatField(null=True)),
                ('arsenic_maximum', models.FloatField(null=True)),
                ('arsenic_std', models.FloatField(null=True)),
                ('cadmium_mean', models.FloatField(null=True)),
                ('cadmium_minimum', models.FloatField(null=True)),
                ('cadmium_maximum', models.FloatField(null=True)),
                ('cadmium_std', models.FloatField(null=True)),
                ('lead_mean', models.FloatField(null=True)),
                ('lead_minimum', models.FloatField(null=True)),
                ('lead_maximum', models.FloatField(null=True)),
                ('lead_std', models.FloatField(null=True)),
                ('manganese_mean', models.FloatField(null=True)),
                ('manganese_minimum', models.FloatField(null=True)),
                ('manganese_maximum', models.FloatField(null=True)),
                ('manganese_std', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'db_table': 'drf_ncwellwise_triangle_20102019_geom',
                'managed': False,
            },
        ),
    ]
